name: CI test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Dependencies
        run: |
          sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
          libxft-dev libxext-dev python libssl-dev
          sudo apt-get install gfortran libpcre3-dev \
          xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
          libmysqlclient-dev libfftw3-dev libcfitsio-dev \
          graphviz-dev libavahi-compat-libdnssd-dev \
          libldap2-dev python-dev libxml2-dev libkrb5-dev \
          libgsl0-dev qtwebengine5-dev
      - name: Install ROOT   
        run: |
           wget https://root.cern/download/root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
           tar -xzvf root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
      - name: Clean & Source 
        run: |
           rm -f root_v6.24.02.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
           source root/bin/thisroot.sh
           . bin/thisroot.sh
           export ROOTSYS=/usr/local/root
           export PATH=$PATH:$ROOTSYS/bin
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOTSYS/lib
      - name: Test ROOT
        run: |
           root
           
           

