name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Dependencies
        run: |
          sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
          libxft-dev libxext-dev python libssl-dev
          sudo apt-get install gfortran libpcre3-dev \
          xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
          libmysqlclient-dev libfftw3-dev libcfitsio-dev \
          graphviz-dev libavahi-compat-libdnssd-dev \
          libldap2-dev python-dev libxml2-dev libkrb5-dev \
          libgsl0-dev qtwebengine5-dev
      - name: Install ROOT   
        run: |
           git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src
           mkdir root_build root_install && cd root_build
           cmake -DCMAKE_INSTALL_PREFIX=../root_install ../root_src
           cmake --build . -- install -j4
           source ../root_install/bin/thisroot.sh
      - name: Test ROOT
        run: |
           root
           
           


